# Generated by Django 6.0 on 2025-12-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='body_color',
            field=models.CharField(blank=True, default='#333333', max_length=7, verbose_name='Цвет текста'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_color',
            field=models.CharField(blank=True, default='#000000', max_length=7, verbose_name='Цвет заголовка'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='text_color',
            field=models.CharField(blank=True, default='#333333', max_length=7, verbose_name='Цвет текста'),
        ),
        migrations.AddField(
            model_name='director',
            name='bio_color',
            field=models.CharField(blank=True, default='#333333', max_length=7, verbose_name='Цвет биографии'),
        ),
        migrations.AddField(
            model_name='director',
            name='name_color',
            field=models.CharField(blank=True, default='#000000', max_length=7, verbose_name='Цвет имени'),
        ),
    ]
