# Generated by Django 6.0 on 2025-12-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Атауы')),
                ('year', models.CharField(max_length=4, verbose_name='Жыл')),
                ('image', models.ImageField(upload_to='certificates/', verbose_name='Сурет')),
                ('category', models.CharField(choices=[('teachers', 'Мұғалімдер'), ('students', 'Оқушылар')], max_length=20, verbose_name='Категория')),
                ('level', models.CharField(choices=[('district', 'Аудан деңгейі'), ('city', 'Қала деңгейі')], max_length=20, verbose_name='Деңгей')),
                ('order', models.IntegerField(default=0, verbose_name='Реттілік')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған күні')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Өзгертілген күні')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаттар',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
